services:
    api:
        build: .
        container_name: lab10
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/books_db
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - postgres
            - redis
        volumes:
            - .:/app
        restart: always

    postgres:
        image: postgres:14
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: books_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:8
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    locust:
        image: locustio/locust
        container_name: locust
        ports:
            - "8089:8089"
        volumes:
            - ./locustfile.py:/mnt/locust/locustfile.py
        command: -f /mnt/locust/locustfile.py --web-host=0.0.0.0 --host=http://api:5000
        depends_on:
            - api

volumes:
    postgres_data:
    redis_data:
