services:
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: books_db
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    api:
        build: .
        ports:
            - "5000:5000"
        container_name: lab5_api
        environment:
            - MONGO_URI=mongodb://mongo_admin:password@mongo:27017/books_db
        depends_on:
            - mongo
        volumes:
            - .:/app
        restart: always

volumes:
    mongo_data:
