services:
    api:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/books_db
            - FLASK_APP=app.py
            - FLASK_ENV=development
            - FLASK_DEBUG=1
        volumes:
            - .:/app
        restart: always

    db:
        image: postgres:14
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=books_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

volumes:
    postgres_data:
