services:
    api:
        build: .
        container_name: lab7
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/books_db
        depends_on:
            - postgres
        volumes:
            - .:/app
        restart: always

    postgres:
        image: postgres:14
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: books_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
